// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddBinding(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddBinding'](arg1, arg2, arg3);
}

export function GetBindings() {
  return window['go']['main']['App']['GetBindings']();
}

export function ListPorts() {
  return window['go']['main']['App']['ListPorts']();
}

export function RemoveBinding(arg1) {
  return window['go']['main']['App']['RemoveBinding'](arg1);
}

export function StartBinding(arg1) {
  return window['go']['main']['App']['StartBinding'](arg1);
}

export function StopBinding(arg1) {
  return window['go']['main']['App']['StopBinding'](arg1);
}
