// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {engine} from '../models';

export function AddBinding(arg1:string,arg2:number,arg3:string,arg4:engine.SerialConfig):Promise<void>;

export function GetBindings():Promise<Record<string, engine.Binding>>;

export function ListPorts():Promise<Array<engine.SerialPortInfo>>;

export function RemoveBinding(arg1:string):Promise<void>;

export function SaveConfig():Promise<void>;

export function StartBinding(arg1:string):Promise<void>;

export function StopBinding(arg1:string):Promise<void>;
